### PR TITLE
Add glossary

### PR DESCRIPTION
**Pull request by willm30**
Adding a list of technologies we use and further reading. Have I missed anything?

### CODE REVIEW

**Review by ArmandoGraterol — COMMENTED** [review]
I'm neutral about this section. Mostly because yes I think this info is useful, but I think most of it could belong in the `Architecture` section. The subsections that we already have in that section like `Block Ingestor`, `Lambda functions`, etc; explain the most important bits or bigger players in our stack while in a summary list like this one or a mind map, we show the other technologies that we also use in more detail. What do y'all think?

**Comment by willm30** [comment]
@rdig Happy to leave it out.

>And if they're not, than arguably they shouldn't be part of the team.

I disagree with this. I would not expect an entry level developer, for instance, to know much about our stack. (Unless you're suggesting no more entry level devs!)

**Comment by Julianahlk** [comment]
> I disagree with this. I would not expect an entry level developer, for instance, to know much about our stack. (Unless you're suggesting no more entry level devs!)

@rdig I also agree with Will here. I think one of the other purposes of this repo is to help onboard new devs to the team faster. I understand when someone joins the team they should be able to learn/catch up on what we use at Colony but I see no harm on providing a list of all the technologies we use, instead of people having to guess. Once new devs join the team they have in their minds a clear idea of what we use and can get started asap. 

Alternatively, I think @ArmandoGraterol 's suggestion can also work.

**Review by rdig — APPROVED** [review]
I guess there's 2 votes for (arguably 3), against my 1. Majority decides :)

**Review by Julianahlk — APPROVED** [review]

**Comment by willm30** [comment]
I will just wait for @jakubcolony to have his say when he's back (on this and all the others in the repo), then I'll get to merging

**Comment by jakubcolony** [comment]
I agree with @ArmandoGraterol's that this should belong (in the current or slightly amended form) in the Architecture section. I felt like it was missing some important details before I found them here 🙂

**Comment by willm30** [comment]
Moved to architecture overview

**Pull request closed without merging**
