### PR TITLE
Add standard for max function parameters

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

The main motivation is to avoid having functions which can appear ambiguous when used. This will also help decrease the chances of human error when passing arguments to a function.

## Without object parameters

```js
function calculateTotalPrice(price, taxRate, discount, shipping) {
    return (price + (price * taxRate) - discount + shipping);
}

// Usage
const totalPrice = calculateTotalPrice(100, 0.07, 10, 5);
```

## With object parameters

```js
function calculateTotalPrice({ price, taxRate, discount, shipping }) {
    return (price + (price * taxRate) - discount + shipping);
}

// Usage
const totalPrice = calculateTotalPrice({
    price: 100,
    taxRate: 0.07,
    discount: 10,
    shipping: 5
});
```

## Enhancement ticket

[Enable an ESlint rule for max-params ](https://github.com/JoinColony/colonyCDapp/issues/2466)

### CODE REVIEW

**Review by davecreaser — APPROVED** [review]
Personally I'm a big fan of this type of rule. Really helps with readability.

Not 100% sure of the usage when there's only a single field, but it's cool with me, especially since you say 'feel free to use' instead of 'prefer' 😆

Nice initiative overall! 📈

**Comment by chmanie** [comment]
3 is a good number. I concur.

**Review by rdig — APPROVED** [review]
I'm good with this, but please put in a PR for JoinColony/colonyCDapp#2466 (and merge it), before merging this into the living standard

**Comment by rumzledz** [comment]
> I'm good with this, but please put in a PR for [JoinColony/colonyCDapp#2466](https://github.com/JoinColony/colonyCDapp/issues/2466) (and merge it), before merging this into the living standard

All right will do @rdig 👌

**Pull request merged**
